version: '1.0'


# run multip services with docker compose : docker compose up -d postgres redis coinbase-backend coinbase-frontend coinbase-prover-backend coinbase-prover-frontend

services:


## Database Services
  postgres:
    image: postgres:15
    container_name: neuralabs-postgres_db
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/postgres_data:/var/lib/postgresql/data
    networks:
      - neuralabs_coinbase_network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: neuralabs-redis_cache
    env_file:
      - ./database/.env
    ports:
      - "6379:6379"
    volumes:
      - ./database/data/redis_data:/data
    # This ${REDIS_PASSWORD} is evaluated by docker-compose, NOT inside the container
    # command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    # Use sh -c to evaluate the variable inside the container
    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --appendonly yes'
    networks:
      - neuralabs_coinbase_network
    restart: unless-stopped

networks:
  neuralabs_coinbase_network:
    driver: bridge
  traefik-proxy:
    external: true

  