version: '3.8'

# NeuraLabs coinbase Production Deployment
# Run with: docker-compose -f docker-compose-deployment.yaml up -d
#
# Services and Port Assignments:
# ┌─────────────────────┬──────┬─────────────────────────────────────┐
# │ Service             │ Port │ URL/Access                          │
# ├─────────────────────┼──────┼─────────────────────────────────────┤
# │ Frontend            │ 2016 │ https://coinbase.neuralabs.org      │
# │ Backend API         │ 2017 │ https://api.coinbase.neuralabs.org  │
# │ Landing Page        │ 2018 │ https://neuralabs.org (separate)    │
# ├─────────────────────┼──────┼─────────────────────────────────────┤
# │ Internal Services   │      │                                     │
# ├─────────────────────┼──────┼─────────────────────────────────────┤
# │ Redis               │ 2019 │ Internal only                       │
# │ PostgreSQL          │ 2020 │ Internal only                       │
# │ Code Executor       │ 2021 │ Internal/API access[Akash Network]  │
# └─────────────────────┴──────┴─────────────────────────────────────┘

services:

## Frontend Service
  neuralabs-coinbase-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neuralabs-coinbase-frontend
    ports:
      - "2016:80"
    networks:
      - neuralabs_network
      - traefik-proxy
    restart: unless-stopped
    depends_on:
      - neuralabs-coinbase-backend
    labels:
      - "traefik.enable=true"
      # Service
      - "traefik.http.services.neuralabs-frontend-coinbase.loadbalancer.server.port=80"
      
      # Router config
      - "traefik.http.routers.neuralabs-frontend-coinbase.rule=Host(`app.neuralabs.org`)"
      - "traefik.http.routers.neuralabs-frontend-coinbase.entrypoints=websecure"
      - "traefik.http.routers.neuralabs-frontend-coinbase.tls=true"
      - "traefik.http.routers.neuralabs-frontend-coinbase.tls.certresolver=letsencrypt"

      # Connect router to service
      - "traefik.http.routers.neuralabs-frontend-coinbase.service=neuralabs-frontend-coinbase"

## Backend Service
  neuralabs-coinbase-backend:
    build:
      context: ./neuralabs-backend
      dockerfile: Dockerfile
    container_name: neuralabs-coinbase-backend
    ports:
      - "2017:8000"
    networks:
      - neuralabs_network
      - traefik-proxy
    restart: unless-stopped
    depends_on:
      - neuralabs-coinbase-postgres
      - neuralabs-coinbase-redis
      - neuralabs-coinbase-executor
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./neuralabs-backend/logs:/app/logs
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--access-logfile", "logs/access.log", "--error-logfile", "logs/error.log", "app:app"]
    labels:
      - "traefik.enable=true"
      # Service
      - "traefik.http.services.neuralabs-backend-coinbase.loadbalancer.server.port=8000"
      # CORS middleware
      - "traefik.http.middlewares.neuralabs-backend-coinbase-cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.neuralabs-backend-coinbase-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.neuralabs-backend-coinbase-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.neuralabs-backend-coinbase-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.neuralabs-backend-coinbase-cors.headers.accesscontrolallowcredentials=true"
      
      # Router config
      - "traefik.http.routers.neuralabs-backend-coinbase.rule=Host(`api.app.neuralabs.org`)"
      - "traefik.http.routers.neuralabs-backend-coinbase.entrypoints=websecure"
      - "traefik.http.routers.neuralabs-backend-coinbase.tls=true"
      - "traefik.http.routers.neuralabs-backend-coinbase.tls.certresolver=letsencrypt"

      # Connect router to service and middleware
      - "traefik.http.routers.neuralabs-backend-coinbase.service=neuralabs-backend-coinbase"
      - "traefik.http.routers.neuralabs-backend-coinbase.middlewares=neuralabs-backend-coinbase-cors"

## HPC Execution Engine
  neuralabs-coinbase-executor:
    build:
      context: ./hpc-execution-node-backend/code_executor
      dockerfile: Dockerfile
    container_name: neuralabs-coinbase-executor
    ports:
      - "2021:8001"
    networks:
      - neuralabs_network
    restart: unless-stopped
    env_file:
      - ./hpc-execution-node-backend/code_executor/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./hpc-execution-node-backend/code_executor/logs:/app/logs
    command: ["gunicorn", "--bind", "0.0.0.0:8001", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--access-logfile", "logs/access.log", "--error-logfile", "logs/error.log", "app:app"]

## Database Services
  neuralabs-coinbase-postgres:
    image: postgres:15
    container_name: neuralabs-coinbase-postgres
    env_file:
      - ./database/.env
    ports:
      - "2020:5432"
    volumes:
      - ./database/data/postgres_data:/var/lib/postgresql/data
    networks:
      - neuralabs_network
    restart: unless-stopped

  neuralabs-coinbase-redis:
    image: redis:7
    container_name: neuralabs-coinbase-redis
    env_file:
      - ./database/.env
    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --appendonly yes'
    ports:
      - "2019:6379"
    volumes:
      - ./database/data/redis_data:/data
    networks:
      - neuralabs_network
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:

networks:
  neuralabs_network:
    driver: bridge
  traefik-proxy:
    external: true